[project]
name = "osl"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "transformers[torch]>=4.46.1",
]

[tool.uv]
dev-dependencies = [
    "ipykernel==6.29.5",
    "ipython==8.27.0",
    "ipywidgets==8.1.5",
]